// Code generated by "stringer -type=Err"; DO NOT EDIT

package radio

import "fmt"

const _Err_name = "ErrMissingErrBadcallErrTimeout"

var _Err_index = [...]uint8{0, 10, 20, 30}

func (i Err) String() string {
	i -= 1
	if i >= Err(len(_Err_index)-1) {
		return fmt.Sprintf("Err(%d)", i+1)
	}
	return _Err_name[_Err_index[i]:_Err_index[i+1]]
}
